football_memories/administration/routes.py
from flask import (render_template,
                   redirect, url_for, Blueprint, session)
from football_memories import mongo

# Create an administration object as a blueprint
administration = Blueprint('administration', __name__)


@administration.route("/")
@administration.route("/home")
def home() -> object:
    """
    This function displays the last three memories on the index template
    :return render_template of index.html
    """
    # Get the last three memories added to the memories collection
    three_latest_memories = list(mongo.db.memories.find().
                                 sort("_id", -1).limit(3))
    return render_template("administration/index.html",
                           memories=three_latest_memories)


@administration.route("/terms_and_conditions")
def terms_and_conditions() -> object:
    """
    This function renders the terms and conditions template
    :return render_template of terms_and_conditions.html
    """
    return render_template("administration/terms_and_conditions.html")


@administration.route("/privacy_policy")
def privacy_policy() -> object:
    """
    This function renders the privacy policy template
    :return render_template of privacy_policy.html
    """
    return render_template("administration/privacy_policy.html")


@administration.route("/dashboard")
def dashboard() -> object:
    """
    This function renders the dashboard template with information
    from five queries(all counts) of the users, tournaments, memories
    comments and ratings collection
    :return render_template of dashboard.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    number_of_users = mongo.db.users.count()
    number_of_tournaments = mongo.db.tournaments.count()
    number_of_memories = mongo.db.memories.count()
    number_of_comments = mongo.db.comments.count()
    number_of_ratings = mongo.db.ratings.count()
    return render_template("administration/dashboard.html",
                           number_of_users=number_of_users,
                           number_of_tournaments=number_of_tournaments,
                           number_of_memories=number_of_memories,
                           number_of_comments=number_of_comments,
                           number_of_ratings=number_of_ratings)

football_memories/memories/routes.py
from flask import (flash, render_template,
                   redirect, request, url_for, Blueprint, session)
from bson.objectid import ObjectId
from flask_paginate import Pagination
from football_memories import mongo
from football_memories.util import util

# Create a memories object as a blueprint
memories = Blueprint('memories', __name__)


@memories.route("/get_memories")
def get_memories():
    """
    This function renders the memories template to display all memories for
    all users and displays pagination if the amount is greater
    than three memories
    :return render_template of memories.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    offset, per_page, page = util.setup_pagination()
    # Get the users details
    username = session["user"]
    user = mongo.db.users.find_one({"username": username})
    # Get all memories and the memory count
    total_memories = mongo.db.memories.find().count()
    memories_sorted_by = mongo.db.memories.find().sort("_id", -1)
    memories_paginated = memories_sorted_by[offset: offset + per_page]
    pagination = Pagination(page=page, per_page=per_page,
                            total=total_memories, css_framework='bootstrap')
    # Render the memories template with the relevant parameters
    return render_template("memories/memories.html",
                           memories=memories_paginated,
                           page=page,
                           per_page=per_page,
                           pagination=pagination, user=user,
                           selected="get_memories")


@memories.route("/get_memory/<id>")
def get_memory(id: object) -> object:
    """
    This function renders the memory template to display memory information
    for a selected memory.
    :param id: memory identifier
    :return render_template of memory.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    # Get the average rating for the selected memory and setup Pagination
    round_av_rating = calculate_average_rating(id)
    offset, per_page, page = util.setup_pagination()
    try:
        # Get the memory information and associated comments
        memory = mongo.db.memories.find_one({"_id": ObjectId(id)})
        comments = mongo.db.comments.find({"memory_id": id}).sort("_id", -1)
        total_comments = mongo.db.comments.find({"memory_id": id}).count()
        # Get the current view count of the memory, and increment
        view_count = memory['memory_view_count']
        new_view_count = view_count + 1
        # Update the memory view count in the database
        mongo.db.memories.update({"_id": ObjectId(id)},
                                 {"$set":
                                 {"memory_view_count": new_view_count}})
        # Setup pagination for the comments
        comments_paginated = comments[offset: offset + per_page]
        pagination = Pagination(page=page, per_page=per_page,
                                total=total_comments,
                                css_framework='bootstrap')
    except Exception as e:
        flash("An exception occurred when retrieving the memory: " +
              getattr(e, 'message', repr(e)))
    # Render the memory template with the relevant parameters
    return render_template("memories/memory.html", memory=memory,
                           comments=comments_paginated, page=page,
                           per_page=per_page,
                           pagination=pagination,
                           average_rating=round_av_rating)


@memories.route("/get_user_memories")
def get_user_memories() -> object:
    """
    This function returns all memories added by a specific user
    :return render_template of memories.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    # Setup pagination and get the user information
    offset, per_page, page = util.setup_pagination()
    username = session["user"]
    try:
        # Get the memories for the specific user
        total_user_memories = mongo.db.memories.find(
            {"memory_created_by": username}).count()
        user_memories = mongo.db.memories.find(
            {"memory_created_by": username}).sort("_id", -1)
        user_memories_paginated = user_memories[offset: offset + per_page]
        pagination = Pagination(page=page, per_page=per_page,
                                total=total_user_memories,
                                css_framework='bootstrap')
    except Exception as e:
        flash("An exception occurred when retrieving the users memories: " +
              getattr(e, 'message', repr(e)))
    # Render the memories template with the relevant parameters
    return render_template("memories/memories.html",
                           memories=user_memories_paginated,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           selected="get_user_memories")


@memories.route("/add_memory", methods=["GET", "POST"])
def add_memory() -> object:
    """
    This function adds a memory with the information passed down
    from the add memory template
    :return redirect to get_user_memories
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))

    if request.method == "POST":
        # Check if the file type is an allowed image file type
        memory_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('memory_image')

        if memory_image_type not in allowed_image_file_types:
            flash("File type " + memory_image_type +
                  " not allowed," +
                  " allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("memories.get_user_memories"))

    if request.method == "POST":
        try:
            # Store the memory image in an S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('memory_image')
            # Create a memory object with the memory information
            memory = {
                "memory_image": image_url,
                "tournament_name": request.form.get("tournament_name"),
                "memory_name": request.form.get("memory_name"),
                "memory_description": request.form.get("memory_description"),
                "memory_date": request.form.get("memory_date"),
                "memory_stadium": request.form.get("memory_stadium"),
                "memory_view_count": 0,
                "memory_created_by": session["user"]
            }
            # Create the memory in the memories collection in the mongodb
            mongo.db.memories.insert_one(memory)
            flash("Memory Successfully Added")
        except Exception as e:
            flash("An exception occurred when adding the memory: " +
                  getattr(e, 'message', repr(e)))
        # Redirect to the get_user_memories route
        return redirect(url_for("memories.get_user_memories"))
    tournaments = mongo.db.tournaments.find().sort("tournament_name", 1)
    return render_template("memories/add_memory.html",
                           tournaments=tournaments)


@memories.route("/edit_memory/<memory_id>", methods=["GET", "POST"])
def edit_memory(memory_id: object) -> object:
    """
    This function edits a memory with the information passed down
    from the edit memory template
    :param memory_id: memory identifier
    :return redirect to get_user_memories
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    if request.method == "POST":
        # Check if the file type is an allowed image file type
        memory_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('memory_image')
        if memory_image_type not in allowed_image_file_types:
            flash("File type " + memory_image_type +
                  " not allowed," +
                  " allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("memories.get_user_memories"))
        try:
            # Store the memory image in an S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('memory_image')
            # Create a memory_to_update object with the new memory information
            memory_to_update = {
                "memory_image": image_url,
                "tournament_name": request.form.get("tournament_name"),
                "memory_name": request.form.get("memory_name"),
                "memory_description": request.form.get("memory_description"),
                "memory_date": request.form.get("memory_date"),
                "memory_stadium": request.form.get("memory_stadium"),
                "memory_created_by": session["user"],
                "memory_view_count": 0
            }
            # Update the memory in the memories collection in the mongodb
            mongo.db.memories.update({"_id": ObjectId(memory_id)},
                                     memory_to_update)
            flash("Memory Successfully Updated")
        except Exception as e:
            flash("An exception occurred when updating the tournament: " +
                  getattr(e, 'message', repr(e)))
        # Redirect to the get_user_memories route
        return redirect(url_for("memories.get_user_memories"))
    memory = mongo.db.memories.find_one({"_id": ObjectId(memory_id)})
    tournaments = mongo.db.tournaments.find().sort("tournament_name", 1)
    return render_template("memories/edit_memory.html",
                           memory=memory,
                           tournaments=tournaments)


@memories.route("/delete_memory/<memory_id>")
def delete_memory(memory_id: object) -> object:
    """

football_memories/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Metadata -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="A site for football fans to add, comment and rate football memories">
    <meta name="keywords" content="football,soccer,images,memories"> 
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon/favicon.png') }}">
    {% block styles %}
    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Font Awesome css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha512-xA6Hp6oezhjd6LiLZynuukm80f8BoZ3OpcEYaqKoCV3HKQDrYjDE1Gu8ocxgxoXmwmSzM4iqPvCsOkQNiu41GA==" crossorigin="anonymous" type="text/css">
    <!-- User style css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock %}
  </head>
  <!-- Body with hero image -->
  <body class="hero-image">
    <!-- Navigation Bar -->
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <div class="navbar-brand"><img src="{{ url_for('static', filename='images/logo/website_logo_grey.jpg') }}" class="logo"  alt="website logo"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if session.user %}
                <!-- User is logged in -->
                <li class="nav-item nav-font"><a href="{{ url_for('memories.get_memories') }}" class="nav-link {% block nav_get_user_memories %}{% endblock %}" aria-current="page">Memories</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('memories.add_memory') }}" class="nav-link {% block nav_add_memory %}{% endblock %}" aria-current="page">Add Memory</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('tournaments.get_tournaments') }}" class="nav-link {% block nav_tournaments %}{% endblock %}" aria-current="page">Tournaments</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('authentication.profile', username=session['user']) }}" class="nav-link {% block nav_profile %}{% endblock %}" aria-current="page">Profile</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('administration.dashboard') }}" class="nav-link {% block nav_dashboard %}{% endblock %}" aria-current="page">Dashboard</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('authentication.logout') }}" class="nav-link  {% block nav_logout %}{% endblock %}" aria-current="page">Log Out</a></li>   
              {% else %}
                <!-- User is not logged in -->
                <li class="nav-item"><a class="nav-link nav-font {% block nav_home %}{% endblock %}" aria-current="page" href="{{ url_for('administration.home') }}">Home</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('authentication.login') }}" class="nav-link {% block nav_login %}{% endblock %}" aria-current="page">Log In</a></li>
                <li class="nav-item nav-font"><a href="{{ url_for('authentication.register') }}" class="nav-link {% block nav_register %}{% endblock %}" aria-current="page">Register</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <!-- Main content -->
  <main class="main-content">
    <!-- Flash messages -->
    <div class="container" id="flash-messages">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="row flashes">
              <div class="alert alert-success" role="alert">{{ message }}</div>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div> 
    {% block content %}
    {% endblock %}
  </main>
  <!-- Footer Credit: https://jsfiddle.net/bootstrapious/c7ash30w/ -->
  <footer class="bg-light" id="site-footer">
    <div class="container">
      <div class="row py-3">
        <!-- Logo and social media links -->
        <div class="col-lg-4 col-md-4 mb-4 mb-lg-0"><img src="{{ url_for('static', filename='images/logo/website_logo_grey.jpg') }}" alt="website logo" class="mb-3 logo">
          <p class="font-italic text-muted footer-font">Football memories is a website for sharing your football memories.</p>
          <ul class="list-inline mt-4">
            <li class="list-inline-item"><a href="http://www.twitter.com" target="_blank" rel="noreferrer" aria-label="Go to our twitter page (opens in new tab)" title="twitter"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="http://www.facebook.com" target="_blank" rel="noreferrer" aria-label="Go to our facebook page (opens in new tab)" title="facebook"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="http://www.instagram.com" target="_blank" rel="noreferrer" aria-label="Go to our instagram page (opens in new tab)" title="instagram"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="http://www.pinterest.com" target="_blank" rel="noreferrer" aria-label="Go to our pinterest page (opens in new tab)" title="pinterest"><i class="fa fa-pinterest"></i></a></li>
            <li class="list-inline-item"><a href="http://www.snapchat.com" target="_blank" rel="noreferrer" aria-label="Go to our snapchat page (opens in new tab)" title="snapchat"><i class="fa fa-snapchat"></i></a></li>
          </ul>
        </div>
        <!-- Terms and conditions and privacy policy links -->
        <div class="col-lg-4 col-md-4 mb-4 mb-lg-0">
          <h2 class="text-uppercase font-weight-bold mb-4 footer-font">Website</h2>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="{{ url_for('administration.terms_and_conditions') }}" class="text-muted footer-font">Terms and Conditions</a></li>
            <li class="mb-2"><a href="{{ url_for('administration.privacy_policy') }}" class="text-muted footer-font">Privacy Policy</a></li>
          </ul>
        </div>
        <!-- Newsletter signup -->
        <div class="col-lg-4 col-md-4 mb-lg-0">
          <h2 class="text-uppercase font-weight-bold mb-4 footer-font">Newsletter</h2>
          <p class="text-muted mb-4 footer-font">Fill in your email address below to receive our monthly newsletter.</p>
          <div class="p-1 rounded border" id="mailing-list">
            <form id="mailinglistform" onsubmit="return sendMail(this);">
              <div class="input-group">       
                <label for="email_address" hidden>Email Address:</label> 
                <input type="email" placeholder="Email address" id="email_address" name="email_address" aria-describedby="newsletter" class="form-control border-0 shadow-0 footer-font" required>
                <div class="input-group-append">
                  <button class="btn btn-primary light-green-one-btn" id="newsletter" type="submit" value="newsletter">Signup</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Copyright information -->
    <div class="bg-light py-1">
      <div class="container text-center">
        <p class="mb-0 py-2 footer-font">© 2021 All rights reserved.</p>
      </div>
    </div>
  </footer>
  <!-- End -->
  {% block scripts %}
  <!-- JQuery javascript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <!-- FontAwesome javascript -->
  <script src="https://kit.fontawesome.com/9e31b09f8c.js" crossorigin="anonymous"></script>
  <!-- EmailJS javascript library-->
  <script src="https://cdn.jsdelivr.net/npm/emailjs-com@2/dist/email.min.js"></script>
  <!-- Bootstrap javascript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <!-- Authentication javascript -->
  <script src="{{ url_for('static', filename='js/authentication.js') }}"></script>
  <!-- Send email javascript -->
  <script src="{{ url_for('static', filename='js/send_email.js') }}"></script>
  {% endblock %}
  </body>
</html>