football_memories/memories/routes.py
from flask import (flash, render_template,
                   redirect, request, url_for, Blueprint, session)
from bson.objectid import ObjectId
from flask_paginate import Pagination
from football_memories import mongo
from football_memories.util import util

# Create a memories object as a blueprint
memories = Blueprint('memories', __name__)


@memories.route("/get_memories")
def get_memories():
    """
    This function renders the memories template to display all memories for
    all users and displays pagination if the amount is greater
    than three memories
    :return render_template of memories.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    offset, per_page, page = util.setup_pagination()
    # Get the users details
    username = session["user"]
    user = mongo.db.users.find_one({"username": username})
    # Get all memories and the memory count
    total_memories = mongo.db.memories.find().count()
    memories_sorted_by = mongo.db.memories.find().sort("_id", -1)
    memories_paginated = memories_sorted_by[offset: offset + per_page]
    pagination = Pagination(page=page, per_page=per_page,
                            total=total_memories, css_framework='bootstrap')
    # Render the memories template with the relevant parameters
    return render_template("memories/memories.html",
                           memories=memories_paginated,
                           page=page,
                           per_page=per_page,
                           pagination=pagination, user=user,
                           selected="get_memories")


@memories.route("/get_memory/<id>")
def get_memory(id: object) -> object:
    """
    This function renders the memory template to display memory information
    for a selected memory.
    :param id: memory identifier
    :return render_template of memory.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    # Get the average rating for the selected memory and setup Pagination
    round_av_rating = calculate_average_rating(id)
    offset, per_page, page = util.setup_pagination()
    try:
        # Get the memory information and associated comments
        memory = mongo.db.memories.find_one({"_id": ObjectId(id)})
        comments = mongo.db.comments.find({"memory_id": id}).sort("_id", -1)
        total_comments = mongo.db.comments.find({"memory_id": id}).count()
        # Get the current view count of the memory, and increment
        view_count = memory['memory_view_count']
        new_view_count = view_count + 1
        # Update the memory view count in the database
        mongo.db.memories.update({"_id": ObjectId(id)},
                                 {"$set":
                                 {"memory_view_count": new_view_count}})
        # Setup pagination for the comments
        comments_paginated = comments[offset: offset + per_page]
        pagination = Pagination(page=page, per_page=per_page,
                                total=total_comments,
                                css_framework='bootstrap')
    except Exception as e:
        flash("An exception occurred when retrieving the memory: " +
              getattr(e, 'message', repr(e)))
    # Render the memory template with the relevant parameters
    return render_template("memories/memory.html", memory=memory,
                           comments=comments_paginated, page=page,
                           per_page=per_page,
                           pagination=pagination,
                           average_rating=round_av_rating)


@memories.route("/get_user_memories")
def get_user_memories() -> object:
    """
    This function returns all memories added by a specific user
    :return render_template of memories.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    # Setup pagination and get the user information
    offset, per_page, page = util.setup_pagination()
    username = session["user"]
    try:
        # Get the memories for the specific user
        total_user_memories = mongo.db.memories.find(
            {"memory_created_by": username}).count()
        user_memories = mongo.db.memories.find(
            {"memory_created_by": username}).sort("_id", -1)
        user_memories_paginated = user_memories[offset: offset + per_page]
        pagination = Pagination(page=page, per_page=per_page,
                                total=total_user_memories,
                                css_framework='bootstrap')
    except Exception as e:
        flash("An exception occurred when retrieving the users memories: " +
              getattr(e, 'message', repr(e)))
    # Render the memories template with the relevant parameters
    return render_template("memories/memories.html",
                           memories=user_memories_paginated,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           selected="get_user_memories")


@memories.route("/add_memory", methods=["GET", "POST"])
def add_memory() -> object:
    """
    This function adds a memory with the information passed down
    from the add memory template
    :return redirect to get_user_memories
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))

    if request.method == "POST":
        # Check if the file type is an allowed image file type
        memory_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('memory_image')

        if memory_image_type not in allowed_image_file_types:
            flash("File type " + memory_image_type +
                  " not allowed," +
                  " allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("memories.get_user_memories"))

    if request.method == "POST":
        try:
            # Store the memory image in an S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('memory_image')
            # Create a memory object with the memory information
            memory = {
                "memory_image": image_url,
                "tournament_name": request.form.get("tournament_name"),
                "memory_name": request.form.get("memory_name"),
                "memory_description": request.form.get("memory_description"),
                "memory_date": request.form.get("memory_date"),
                "memory_stadium": request.form.get("memory_stadium"),
                "memory_view_count": 0,
                "memory_created_by": session["user"]
            }
            # Create the memory in the memories collection in the mongodb
            mongo.db.memories.insert_one(memory)
            flash("Memory Successfully Added")
        except Exception as e:
            flash("An exception occurred when adding the memory: " +
                  getattr(e, 'message', repr(e)))
        # Redirect to the get_user_memories route
        return redirect(url_for("memories.get_user_memories"))
    tournaments = mongo.db.tournaments.find().sort("tournament_name", 1)
    return render_template("memories/add_memory.html",
                           tournaments=tournaments)


@memories.route("/edit_memory/<memory_id>", methods=["GET", "POST"])
def edit_memory(memory_id: object) -> object:
    """
    This function edits a memory with the information passed down
    from the edit memory template
    :param memory_id: memory identifier
    :return redirect to get_user_memories
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))
    if request.method == "POST":
        # Check if the file type is an allowed image file type
        memory_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('memory_image')
        if memory_image_type not in allowed_image_file_types:
            flash("File type " + memory_image_type +
                  " not allowed," +
                  " allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("memories.get_user_memories"))
        try:
            # Store the memory image in an S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('memory_image')
            # Create a memory_to_update object with the new memory information
            memory_to_update = {
                "memory_image": image_url,
                "tournament_name": request.form.get("tournament_name"),
                "memory_name": request.form.get("memory_name"),
                "memory_description": request.form.get("memory_description"),
                "memory_date": request.form.get("memory_date"),
                "memory_stadium": request.form.get("memory_stadium"),
                "memory_created_by": session["user"],
                "memory_view_count": 0
            }
            # Update the memory in the memories collection in the mongodb
            mongo.db.memories.update({"_id": ObjectId(memory_id)},
                                     memory_to_update)
            flash("Memory Successfully Updated")
        except Exception as e:
            flash("An exception occurred when updating the tournament: " +
                  getattr(e, 'message', repr(e)))
        # Redirect to the get_user_memories route
        return redirect(url_for("memories.get_user_memories"))
    memory = mongo.db.memories.find_one({"_id": ObjectId(memory_id)})
    tournaments = mongo.db.tournaments.find().sort("tournament_name", 1)
    return render_template("memories/edit_memory.html",
                           memory=memory,
                           tournaments=tournaments)


@memories.route("/delete_memory/<memory_id>")
def delete_memory(memory_id: object) -> object:
    """

football_memories/templates/memories/add_memory.html
{% extends "base.html" %}
{% block title %}Add Memory{% endblock %}
{% block nav_add_memory %}active{% endblock %}
{% block content %}
<div class="flex-wrapper">
    <div class="container common-holder common-holder-width">
        <!-- Add Memory header-->
        <div class="h1-header">   
            <h1>Add Memory</h1>
        </div>
        <!-- Add Memory form-->
        <div class="common-body">
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('memories.add_memory') }}" class="needs-validation" novalidate>
                <!-- Tournament name, display dropdown of tournaments-->
                <div class="row mt-3 form-group">
                    <label for="tournament_name" class="form-label col-4">Tournament Name</label>
                    <div class="col-8">
                        <select id="tournament_name" name="tournament_name" class="form-control validate" required>
                        <option value="" disabled selected>Choose Tournament</option>
                            {% for tournament in tournaments %}
                                <option value="{{ tournament.tournament_name }}">{{ tournament.tournament_name }}</option>
                            {% endfor %}
                        </select>
                    </div>    
                </div> 
                <!-- Memory image and validation-->
               <div class="row mt-3 form-group">
                    <label for="memory_image" class="form-label col-4">Memory Image</label>
                    <div class="col-8">
                        <input class="form-control validate" type="file" id="memory_image" name="memory_image" value="file" required>
                        <div id="memory_image_help" class="form-text">
                            Only image files(jpg, JPG, png, PNG) will be accepted
                        </div>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please upload a memory image
                        </div>
                    </div>
                </div>
                <!-- Memory name and validation-->
                <div class="row mt-3 form-group">
                    <label for="memory_name" class="form-label col-4">Memory Name</label>
                    <div class="col-8">
                        <input class="form-control" id="memory_name" name="memory_name" type="text" aria-describedby="memory_name" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory name
                        </div>
                    </div>
                </div> 
                <!-- Memory description(textarea) and validation-->
                <div class="row mt-3 form-group">
                    <label for="memory_description" class="form-label col-4">Memory Description</label>
                    <div class="col-8">
                        <textarea class="form-control" id="memory_description" name="memory_description" rows="3" required></textarea>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory description
                        </div>
                    </div>
                </div>
                <!-- Date and validation-->
                <div class="row mt-3 form-group">
                    <label for="memory_date" class="col-4 col-form-label">Date</label>
                    <div class="col-8">
                        <input class="form-control" type="date" id="memory_date" name="memory_date" required> 
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory date
                        </div>
                    </div>
                </div>     
                <!-- Stadium and validation-->         
                <div class="row mt-3 form-group">
                    <label for="memory_stadium" class="col-4 col-form-label">Stadium</label>
                    <div class="col-8">
                        <input class="form-control" name="memory_stadium" type="text" id="memory_stadium" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a stadium
                        </div>
                    </div>
                </div> 
                <!-- Submit and cancel button -->
                <div class="submit-holder">
                    <a href="{{ url_for('memories.get_user_memories') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-primary light-green-one-btn">Add Memory</button>
                </div>
            </form>
        </div>
    </div>    
</div>     
{% endblock %}

football_memories/templates/memories/edit_memory.html
{% extends "base.html" %}
{% block title %}Edit Memory{% endblock %}
{% block content %}
<div class="flex-wrapper">
    <div class="container common-holder common-holder-width">
        <!-- Edit Memory header-->
        <div class="h1-header">   
            <h1>Edit Memory</h1>
        </div>
        <!-- Edit Memory form-->
        <div class="common-body">
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('memories.edit_memory', memory_id=memory._id) }}" class="needs-validation" novalidate>                                                              
                <div class="row mt-3 form-group">
                    <!-- Tournament name, displays selected tournament-->
                    <label for="tournament_name" class="form-label col-4">Tournament Name</label>
                    <div class="col-8">
                        <select id="tournament_name" name="tournament_name" class="validate form-control" required>
                            <option value="" disabled hidden>Choose a tournament</option>
                                {% for tournament in tournaments %}
                                    {% if tournament.tournament_name == memory.tournament_name %}
                                        <option value="{{ tournament.tournament_name }}" selected>{{ tournament.tournament_name }}</option>
                                    {% else %}
                                        <option value="{{ tournament.tournament_name }}">{{ tournament.tournament_name }}</option>
                                    {% endif %}
                                {% endfor %}
                        </select>
                    </div>    
                </div>
               <div class="row mt-3 form-group">
                   <!-- Memory image and validation-->
                    <label for="memory_image" class="form-label col-4">Memory Image</label>
                    <div class="col-8">
                        <input class="form-control validate" type="file" id="memory_image" name="memory_image" required>
                        <div id="memory_image_help" class="form-text">
                            Only image files(jpg, JPG, png, PNG) will be accepted
                        </div>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please upload a memory image
                        </div>
                    </div>
                </div>
                <div class="row mt-3 form-group">
                    <!-- Memory name and validation-->
                    <label for="memory_name" class="form-label col-4">Memory Name</label>
                    <div class="col-8">
                        <input class="form-control" id="memory_name" name="memory_name" type="text" aria-describedby="memory_name" value="{{ memory.memory_name }}" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory name
                        </div>
                    </div>
                </div>
                <div class="row mt-3 form-group">
                    <!-- Memory description and textarea-->
                    <label for="memory_description" class="form-label col-4">Memory Description</label>
                    <div class="col-8">
                        <textarea class="form-control" id="memory_description" name="memory_description" rows="3" aria-describedby="memory_description" required>{{ memory['memory_description'] }}</textarea>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory description
                        </div>
                    </div>
                </div>
                <div class="row mt-3 form-group">
                    <!-- Memory date-->
                    <label for="memory_date" class="col-4 col-form-label">Date</label>
                    <div class="col-8">
                    <input class="form-control" type="date" id="memory_date" name="memory_date" value="{{ memory.memory_date  }}" required> 
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a memory date
                        </div>
                    </div>
                </div>   
               <div class="row mt-3 form-group">
                    <!-- Memory stadium-->
                    <label for="memory_stadium" class="col-4 col-form-label">Stadium</label>
                    <div class="col-8">
                        <input class="form-control" name="memory_stadium" type="text" id="memory_stadium" value="{{ memory.memory_stadium }}" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                        <div class="invalid-feedback">
                            Please enter a stadium
                        </div>
                    </div>
                </div>
                <!-- Save changes and cancel button -->
                <div class="submit-holder">
                    <a href="{{ url_for('memories.get_user_memories') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-primary light-green-one-btn">Save Changes</button>
                </div>
            </form>
        </div>
    </div>    
</div>        
{% endblock %}

football_memories/templates/memories/memories.html
{% extends "base.html" %}
{% block title %}Memories{% endblock %}
{% block nav_get_user_memories %}active{% endblock %}
{% block content %}
<div class="flex-wrapper-auth">
    <div class="container common-holder">
        <!-- Memories header-->
        <div class="h1-header">   
            <h1>Memories</h1>
        </div>
        <!-- List of memories, three displayed per page -->
        <div class="container" id="memory-list">
            <div id="myBtnContainer">
                <!-- Filters-->
                <div class="row" id="filters">
                    <div class="col-lg-1">
                        <h2 class="h2-header">Filters:</h2>
                    </div>
                    <div class="col-lg-11">
                        <a class="btn btn-light phone-font"  {% if selected == "get_memories" %} id="selected" {% endif %} href="{{ url_for('memories.get_memories') }}"> All Memories</a>
                        <a  class="btn btn-light phone-font" {% if selected == "get_user_memories" %} id="selected" {% endif %} href="{{ url_for('memories.get_user_memories') }}"> My Memories</a>
                    </div>
                </div>   
                <!-- Search area and reset button-->   
                <div class="row">
                    <div class="col-lg-1">
                        <h2 class="h2-header">Search:</h2>
                    </div> 
                    <div class="col-lg-9 col-md-12" id="search-bar">  
                        <form action="{{ url_for('memories.search') }}" method="POST">         
                            <input class="form-control validate" type="text" aria-label="Search" name="query" id="query" minlength="3" required value="{{query}}">
                                <div id="search-and-reset">
                                    <button type="submit" class="light-blue darken-1 btn text-shadow">
                                        <i class="fas fa-search left"></i> Search
                                    </button>
                                    <a class="btn btn-light phone-font" href="{{ url_for('memories.get_memories') }}">Reset</a>
                                </div>    
                        </form>
                    </div> 
                </div>   
            </div>  
            <div class="container">
                <div class="row">
                    <!-- Gallery item, Credit: https://bootstrapious.com/p/bootstrap-photo-gallery  -->
                    {% for memory in memories %}
                    <div class="col col-lg-4 col-md-6 mb-4">
                        <div class="bg-white rounded shadow-sm" id="full-card">
                            <!-- Memory image -->
                            <a href="/get_memory/{{ memory._id }}">
                                <img src="{{ memory.memory_image }}" alt="{{ memory.memory_name }}" class="img-fluid card-img-top">
                            </a>
                            <!-- Memory details -->
                            <div class="p-4 memory-details">
                                <h2> <a href="/get_memory/{{ memory._id }}" class="text-dark">{{ memory.memory_name }}</a></h2>
                                <p class="small text-muted mb-0">Tournament: {{ memory.tournament_name }}</p>
                                <p class="small text-muted mb-0">Description: {{ memory.memory_description }}</p>
                                <p class="small text-muted mb-0">Description: {{ memory.memory_stadium }}</p>
                                <p class="small text-muted mb-0">Date: {{ memory.memory_date }}</p>
                                <p class="small text-muted mb-0">Uploaded By: {{ memory.memory_created_by }}</p>
                                {% if (session.user|lower == memory.memory_created_by|lower) or (user.user_type == "admin_user") %}
                                <div class="d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4">
                                    <div class="row" id="edit_and_delete_memory_buttons">
                                    {% if (session.user|lower == memory.memory_created_by|lower) %}
                                        <!-- A user who created a memory can edit -->
                                        <div class="col-md-6 col-sm-12 center-div">
                                            <a id="edit_memory_button" class="btn btn-success light-green-one-btn" href="{{ url_for('memories.edit_memory', memory_id=memory._id) }}">Edit</a>
                                        </div>
                                    {% endif %}
                                        <!-- An admin user who memory creator can delete a memory -->
                                        <div class="col-md-6 col-sm-12 center-div">
                                            <button type="submit" id="delete_memory_button" class="btn btn-danger" data-bs-toggle="modal" aria-labelledby="deleteMemoryModal{{ memory._id }}" data-bs-target="#deleteMemoryModal{{ memory._id }}">Delete</button>
                                            <!-- Delete memory modal -->
                                            <div class="modal fade" id="deleteMemoryModal{{ memory._id }}" tabindex="-1" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h2 class="modal-title">Delete Memory</h2>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to delete this memory?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <!-- Close and delete memory buttons -->
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                        <a href="{{ url_for('memories.delete_memory', memory_id=memory._id) }}" class="btn btn-primary light-green-one-btn">Delete Memory</a>
                                                    </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>    
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Pagination -->
            <div class="container">
                <div class="row d-flex align-items-center justify-content-between rounded-pill bg-light px-3 py-2 mt-4">
                    <div class="col-md-6 col-sm-12">
                         {{ pagination.links }} 
                    </div>
                    <div class="col-md-6 col-sm-12" id="pagin-info">
                        {{ pagination.info }}  
                    </div>
                </div>
            </div>  
        </div>     
    </div>
</div>
{% endblock %}