football_memories/tournaments/routes.py
from bson.objectid import ObjectId
from flask import (flash, render_template,
                   redirect, request, url_for, Blueprint, session)
from flask_paginate import Pagination
from football_memories import mongo
from football_memories.util import util

# Create a tournaments object as a blueprint
tournaments = Blueprint('tournaments', __name__)


@tournaments.route("/get_tournaments")
def get_tournaments() -> object:
    """
    This function renders the tournament template with all tournaments
    in the tournament collection, the most recent added is displayed first
    :return render_template of tournament.html
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))

    # Setup pagination
    offset, per_page, page = util.setup_pagination()

    # Get the user information
    username = session["user"]
    user = mongo.db.users.find_one({"username": username})

    # Get the tournament information and count
    total_tournaments = mongo.db.tournaments.find().count()
    tournaments = list(mongo.db.tournaments.find().sort("_id", -1))
    tournaments_paginated = tournaments[offset: offset + per_page]
    pagination = Pagination(page=page, per_page=per_page,
                            total=total_tournaments, css_framework='bootstrap')

    # Render the tournament template with the relevant tournament information
    return render_template("tournaments/tournament.html",
                           tournaments=tournaments_paginated,
                           page=page,
                           per_page=per_page,
                           pagination=pagination, user=user)


@tournaments.route("/add_tournament", methods=["GET", "POST"])
def add_tournament() -> object:
    """
    This function adds a tournament with tournament name and image
    :return redirect to get_tournaments
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))

    if request.method == "POST":

        # Check if the file type is an allowed image file type
        tournament_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('tournament_image')

        if tournament_image_type not in allowed_image_file_types:
            flash("File type " + tournament_image_type +
                  " not allowed," +
                  " allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("tournaments.get_tournaments"))

        # Check if the tournament name already exists in db
        existing_tournament = mongo.db.tournaments.find_one(
            {"tournament_name": request.form.get("tournament_name")})

        # Display a message to the user and redirect to tournaments page
        if existing_tournament:
            flash("Tournament name already exists")
            return redirect(url_for("tournaments.get_tournaments"))
        try:
            # Store the tournament image in the AWS S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('tournament_image')

            # Create a tournament object with a name and image
            tournament = {
                "tournament_name":
                    request.form.get("tournament_name"),
                "tournament_image": image_url
            }
            # Create the tournament in the tournaments collection
            # in mongodb
            mongo.db.tournaments.insert_one(tournament)
            flash("New tournament Added")
        except Exception as e:
            flash("An exception occurred when adding a new tournament: " +
                  getattr(e, 'message', repr(e)))
        # Redirect the user to the get tournaments route
        return redirect(url_for("tournaments.get_tournaments"))

    return render_template("tournaments/add_tournament.html")


@tournaments.route("/edit_tournament/<tournament_id>", methods=["GET", "POST"])
def edit_tournament(tournament_id: object) -> object:
    """
    This function edits a tournament with updated tournament name and image
    :param tournament_id: Identifier of tournament
    :return redirect to get_tournaments
    """
    # Check the user is logged in
    if 'user' not in session:
        return redirect(url_for("administration.home"))

    if request.method == "POST":
        # Check if the file type is an allowed image file type
        tournament_image_type, allowed_image_file_types = \
            util.is_image_type_allowed('tournament_image')

        if tournament_image_type not in allowed_image_file_types:
            flash("File type " + tournament_image_type +
                  " not allowed, " +
                  "allowed file types are: jpg, JPG ,png ,PNG")
            return redirect(url_for("tournaments.get_tournaments"))

        # Check if tournament name already exists in db
        existing_tournament = mongo.db.tournaments.find_one(
            {"tournament_name": request.form.get("tournament_name")})

        if existing_tournament:
            flash("Tournament name already exists")
            return redirect(url_for("tournaments.get_tournaments"))

        try:
            # Store the tournament image in the AWS S3 bucket
            image_url = util.store_image_in_aws_s3_bucket('tournament_image')

            # Create a tournament object with a name and image
            updated_tournament = {
                "tournament_name": request.form.get("tournament_name"),
                "tournament_image": image_url
            }
            # Update the tournament in the tournaments collection
            # in the mongodb
            mongo.db.tournaments.update({"_id": ObjectId(tournament_id)},
                                        updated_tournament)
            flash("Tournament Successfully Updated")
        except Exception as e:
            flash("An exception occurred when editing the tournament: " +
                  getattr(e, 'message', repr(e)))
        # Redirect the user to the get tournaments route
        return redirect(url_for("tournaments.get_tournaments"))

    # Return the selected tournament
    tournament = mongo.db.tournaments.find_one(
                    {"_id": ObjectId(tournament_id)})
    return render_template("tournaments/edit_tournament.html",
                           tournament=tournament)


@tournaments.route("/delete_tournament/<tournament_id>",
                   methods=["GET", "POST"])
def delete_tournament(tournament_id: object) -> object:
    """
    This function deletes a tournament
    :param tournament_id: Identifier of tournament
    :return redirect to get_tournaments
    """
    # Get the tournament information
    tournament = mongo.db.tournaments.find_one(
               {"_id": ObjectId(tournament_id)})
    # Get the number of memories within the tournament
    number_of_memories = mongo.db.memories.find(
                {"tournament_name": tournament['tournament_name']}).count()

    # If the tournament has memories if cannot be deleted
    if number_of_memories > 0:
        flash("A tournament than contains memories cannot be deleted")
    else:
        # Get the count of tournaments in the tournament collection
        number_of_tournaments = mongo.db.tournaments.find().count()
        if number_of_tournaments == 1:
            flash("Cannot delete this tournament as a " +
                  "minimum of one tournament is required")
        else:
            # Delete the tournament from the tournaments collection
            try:
                mongo.db.tournaments.remove({"_id": ObjectId(tournament_id)})
                flash("Tournament Successfully Deleted")
            except Exception as e:
                flash("An exception occurred when deleting the tournament: " +
                      getattr(e, 'message', repr(e)))
    # Redirect to the get tournaments page
    return redirect(url_for("tournaments.get_tournaments"))

football_memories/templates/tournaments/add_tournament.html
{% extends "base.html" %}
{% block title %}Add Tournament{% endblock %}
{% block content %}
<div class="flex-wrapper">
    <div class="container common-holder common-holder-width">
        <!-- Add tournament header -->
        <div class="h1-header">   
            <h1>Add Tournament</h1>
        </div>
        <div class="common-body">
            <!-- Add tournament form -->
            <form  method="POST" enctype="multipart/form-data"  action="{{ url_for('tournaments.add_tournament') }}"  class="needs-validation" novalidate>
                <div class="row mt-3 form-group">
                    <!-- Tournament name with validation -->
                    <label for="tournament_name" class="form-label col-4">Tournament Name</label>
                    <div class="col-8">
                        <input class="form-control" id="tournament_name" name="tournament_name" type="text" aria-describedby="tournament_name" required>
                        <div class="invalid-feedback">
                            Please enter a tournament name
                        </div>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                </div> 
                <div class="row mt-3 form-group">
                    <!-- Tournament image with validation -->
                    <label for="tournament_image" class="form-label col-4">Tournament Image</label>
                    <div class="col-8">
                        <input class="form-control validate" type="file" id="tournament_image" name="tournament_image" aria-describedby="tournament_image" required accept="image/*">
                        <div id="tournament_image_help" class="form-text">
                            Only image files(jpg, JPG, png, PNG) will be accepted
                        </div>
                        <div class="invalid-feedback">
                            Please upload a tournament image
                        </div>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                </div>                   
                <!-- submit and cancel buttons -->
                <div class="submit-holder">
                    <a href="{{ url_for('tournaments.get_tournaments') }}" class="btn btn-danger">Cancel</a>
                    <button type="submit" class="btn btn-primary light-green-one-btn">Add Tournament</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

football_memories/templates/tournaments/edit_tournament.html
{% extends "base.html" %}
{% block title %}Edit Tournament{% endblock %}
{% block content %}
<div class="flex-wrapper">
    <div class="container common-holder common-holder-width">
        <!-- Edit tournament header -->
        <div class="h1-header">   
            <h1>Edit Tournament</h1>
        </div>
        <div class="common-body">
            <!-- Edit tournament form -->
            <form method="POST" enctype="multipart/form-data"  action="{{ url_for('tournaments.edit_tournament', tournament_id=tournament._id) }}"  class="needs-validation" novalidate>
               <div class="row mt-3 form-group">
                   <!-- Tournament name and validation -->
                    <label for="tournament_name" class="form-label col-4">Tournament Name</label>
                    <div class="col-8">
                    <input class="form-control" id="tournament_name" name="tournament_name" type="text" aria-describedby="tournament_name" required value="{{ tournament.tournament_name }}">
                    <div class="invalid-feedback">
                        Please enter a tournament name
                    </div>
                    <div class="valid-feedback">
                        Looks good!
                        </div>
                    </div>
                </div> 
                <div class="row mt-3 form-group">
                    <!-- Tournament image and validation -->
                    <label for="tournament_image" class="form-label col-4">Tournament Image</label>
                    <div class="col-8">
                    <input type="file" class="form-control validate" id="tournament_image" name="tournament_image" aria-describedby="tournament_image" required accept="image/*">
                    <div id="tournament_image_help" class="form-text">
                        Only image files(jpg, JPG, png, PNG) will be accepted
                    </div>
                    <div class="invalid-feedback">
                        Please upload a tournament image
                    </div>
                    <div class="valid-feedback">
                        Looks good!
                        </div>
                    </div>
                </div>               
                <!-- Submit button -->
                <div class="submit-holder">
                    <!-- Submit and cancel buttons -->
                    <div class="col s12 center-align">
                        <a href="{{ url_for('tournaments.get_tournaments') }}" class="btn btn-danger">Cancel</a>
                       <button type="submit" class="btn btn-primary light-green-one-btn">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

football_memories/templates/tournaments/tournament.html
{% extends "base.html" %}
{% block title %}Tournaments{% endblock %}
{% block nav_tournaments %}active{% endblock %}
{% block content %}
<div class="hero-image flex-wrapper">
    <!-- Tournament header -->
    <div class="container common-holder">
        <div class="h1-header">   
            <h1>Tournaments</h1>
        </div>
        <!-- Add Tournament, once the user is an admin user  -->
        {% if (user.user_type == "admin_user") %}
        <div class="row" id="add_tournament">
            <div class="col-12">
                <a href="{{ url_for('tournaments.add_tournament') }}" class="btn btn-primary light-green-one-btn">Add Tournament
                </a>
            </div>
        </div>
        {% endif %}
        <div class="container">
            <div class="row">
                <!-- Display each tournament, three tournaments per page -->
                {% for tournament in tournaments %}
                <div class="col col-lg-4 col-md-6 mb-4">
                    <div class="card">
                        <!-- Tournament image -->  
                        <img class="tournament-image" src={{tournament.tournament_image}}  alt="tournament image {{ tournament.tournament_name }}">  
                        <!-- Tournament name -->         
                        <div class="card-body">
                            <h2 class="card-title">{{ tournament.tournament_name }}</h2>
                        </div>
                        <!-- An admin user can edit or delete a tournament -->  
                        {% if (user.user_type == "admin_user") %}
                        <div class="card-action">
                            <a href="{{ url_for('tournaments.edit_tournament', tournament_id=tournament._id) }}" class="btn btn-primary light-green-one-btn">Edit</a>
                            <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteTournamentModal{{ tournament._id }}">Delete</a>
                            <!-- Delete tournament modal -->
                            <div class="modal fade" id="deleteTournamentModal{{ tournament._id }}" tabindex="-1"  aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h2 class="modal-title">Delete Tournament</h2>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete this tournament?
                                        </div>
                                        <div class="modal-footer">
                                            <!-- Close and delete tournament buttons-->
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                <a href="{{ url_for('tournaments.delete_tournament', tournament_id=tournament._id) }}" class="btn btn-primary light-green-one-btn">Delete Tournament</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>  
                {% endfor %} 
            </div>
            <!-- Pagination -->
            <div class="container">
                <div class="row d-flex align-items-center justify-content-between rounded-pill bg-light py-2 mt-4">
                    <div class="col-md-6 col-sm-12">
                        {{ pagination.links }} 
                    </div>
                    <div class="col-md-6 col-sm-12" id="pagin-info">
                        {{ pagination.info }}  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}